"use strict";

var slices = 8;
//while loop
// while (slices > 0){
//     console.log("I'll have a slice");
//     slices--;
//     console.log(slices);
// }

/**
 * keep track of whats in your cart
 * Ask the user for input
 * get user input
 * declare a user input variable
 * store the input in a variable userInput
 * declare a variable to store the total cart price (accumulator)
 * add cost of a new item to the total
 * keep storing till the user has finished
 * tell the user how to end the program (sentinel value)
 * loop back around till that value has been met
 */
var priceOfItem = parseFloat(prompt("Enter the price of your first item"));
var totalCost = priceOfItem;
alert("The price of your item is $" + priceOfItem);
//while loop
var userInput = "";
while(userInput !== "STOP") {
    userInput = prompt("Enter the price of your next item \r\n Enter \"STOP\" when you are done.");
    if(userInput === "STOP"){
        alert("The total is: $" + totalCost.toFixed(2));
    }
    else {
        priceOfItem = parseFloat(userInput);
        totalCost = totalCost + priceOfItem;
        alert("The total is: $" + totalCost.toFixed(2));
    }
}
//do while loop
var number = Math.floor(Math.random() * 6) + 1;
var guess;
do{
    guess = parseInt(prompt("Enter a number between 1 - 6"));

}while(guess !== number);

alert("Your guess matches the number generated by the computer!");
